spring.application.name=demo

# ビュー名が "jsp/" で始まるものは JSP（src/main/webapp/WEB-INF/jsp/*.jsp）、
# それ以外は Thymeleaf（src/main/resources/templates/*.html）で表示する。
spring.mvc.view.prefix=/WEB-INF/
spring.mvc.view.suffix=.jsp
spring.thymeleaf.excluded-view-names=jsp/*
